"""Compatibility exports for the single shared installed v6 exact-numeric authority."""

from autotrade_numeric.exact_decimal import (
    ExactDecimalError,
    RoundingMode,
    MAX_DECIMAL_TEXT_LENGTH,
    MAX_SIGNIFICANT_DIGITS,
    MAX_SCALE,
    MAX_INTEGER_DIGITS,
    MAX_RATIONAL_DIGITS,
    parse_canonical_decimal_text,
    parse_bounded_exact_decimal,
    parse_bounded_json_number_token,
    parse_bounded_json_integer_token,
    bounded_fraction,
    as_fraction,
    is_exact_decimal_multiple,
    terminating_decimal,
    exact_abs,
    exact_add,
    exact_subtract,
    exact_multiply,
    exact_sum,
    round_fraction_to_quantum,
    canonical_decimal_text,
)

__all__ = [
    "ExactDecimalError",
    "RoundingMode",
    "MAX_DECIMAL_TEXT_LENGTH",
    "MAX_SIGNIFICANT_DIGITS",
    "MAX_SCALE",
    "MAX_INTEGER_DIGITS",
    "MAX_RATIONAL_DIGITS",
    "parse_canonical_decimal_text",
    "parse_bounded_exact_decimal",
    "parse_bounded_json_number_token",
    "parse_bounded_json_integer_token",
    "bounded_fraction",
    "as_fraction",
    "is_exact_decimal_multiple",
    "terminating_decimal",
    "exact_abs",
    "exact_add",
    "exact_subtract",
    "exact_multiply",
    "exact_sum",
    "round_fraction_to_quantum",
    "canonical_decimal_text"
]
